# Generated by Django 3.2.25 on 2024-09-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(db_index=True, max_length=16, unique=True)),
                ('origin_country_id', models.CharField(blank=True, max_length=50, null=True)),
                ('destination_country_id', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=5)),
                ('customer_id', models.UUIDField()),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_slug', models.SlugField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
