# Generated by Django 3.2.25 on 2024-09-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_number_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingnumber',
            name='customer_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackingnumber',
            name='customer_slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackingnumber',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
